### ISSUE TITLE
not finding all matches?

### ISSUE THREAD

**Issue by johnlindquist** [msafi/xvsc#4]
This is trying to find "e", but there are way more "e's" on the page then there are keys to jump to...

![image](https://user-images.githubusercontent.com/36073/30245370-dcc287a2-9594-11e7-9adc-7c44368fcd74.png)

**Comment by msafi** [comment]
Yes, this is kinda how it works. From the README:

> While the other AceJump solutions can jump to a word given a single letter, Find-Jump works better when you type a sequence of characters so that it can narrow down the location to where you want to jump. I made it this way because I believe this provides a better overall experience.

I would recommend giving this new flow a try and see how you like it. 

It's a trade-off between a two-letter sequence to trigger the jump or typing more initially to narrow down the number of hits so that you can get to your target with a single-letter jump. 

For example if you wanna jump to the `e` parameter, type e followed by a space and that will narrow down the search enough so that all the `e` parameters will be highlighted.

**Comment by johnlindquist** [comment]
gotcha, apologies for skipping the readme and making assumptions.

**Comment by msafi** [comment]
@johnlindquist No worries 😀
